### ISSUE TITLE
Support Direct3D 11.1

### ISSUE THREAD

**Issue by MathewSachin** [Screna/Direct3DHook#7]

**Comment by uGiFarukh** [comment]
Some codes are available in the project for DirectX 11.1 implementation. Those are not usable? Have you tried it with any DirectX 11.1 game?

**Comment by MathewSachin** [comment]
I don't have any DirectX 11.1 or 11 game. I need help for that

**Comment by uGiFarukh** [comment]
No problem. I got one game which uses DirectX 11.1 and have to download a game I already knew which uses DirectX 11 version. So I will do that test for you.

**Comment by MathewSachin** [comment]
Thank You for that
